name: Itch
on:
  push:
    branches: ['main']

jobs:
  build:
    name: Deploy to itch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@main

      - name: build 
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version}}

      - run: npm ci
      - run: npm run build

      - name: Deploy to itch
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: browser
          ITCH_GAME: ${{ secrets.ITCH_GAME }}
          ITCH_USER: ${{ secrets.ITCH_USER }}
          PACKAGE: public
